FirstBackEndProj/FirstBackEndProj/Areas/Admin/Controllers/GroupController.cs
using FirstBackEndProj.DAL;
using FirstBackEndProj.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstBackEndProj.Areas.Admin.Controllers
{
    public class GroupController : Controller
    {

        private readonly CoolContext _db = new CoolContext();
        // GET: Admin/Group
        public ActionResult Index()
        {

            var model = _db.AuthGroups.Include("Users").ToList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {

            var model = _db.AuthActions.ToList();
            return View(model);
        }

        [HttpPost]
        public JsonResult Create(AuthGroup group)
        {
            JsonResponse response = new JsonResponse
            {
                Success = false
            };

            if (group == null || string.IsNullOrEmpty(group.Name))
            {
                response.Message = "Group name cannot be empty";
                return Json(response);
            }
            if (group.AuthPermissions == null || group.AuthPermissions.Count == 0)
            {
                response.Message = "At least 1 permission have to choose";
                return Json(response);
            }

            _db.AuthGroups.Add(group);
            _db.SaveChanges();

            response.Success = true;


            return Json(response);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = _db.AuthGroups.Include("AuthPermissions").FirstOrDefault(g => g.Id == Id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.Actions = _db.AuthActions.ToList();
            return View(model);
        }



        [HttpPost]
        public JsonResult Edit(AuthGroup group, AuthPermission[] permissions)
        {

            JsonResponse response = new JsonResponse
            {
                Success = false
            };

            if (_db.AuthGroups.FirstOrDefault(g => g.Name == group.Name && g.Id != group.Id) != null)
            {

                response.Message = "This group is already available";
                return Json(response);
            }

            if (string.IsNullOrEmpty(group.Name))
            {
                response.Message = "Name cannot be empty";
                return Json(response);
            }

            if (permissions == null || permissions.Length == 0)
            {
                response.Message = "Permissions cannot be empty";
                return Json(response);
            }

            var perms = _db.AuthPermissions.Where(p => p.AuthGroupId == group.Id);

            _db.AuthPermissions.RemoveRange(perms);
            _db.AuthPermissions.AddRange(permissions);
            _db.Entry(group).State = System.Data.Entity.EntityState.Modified;
            _db.SaveChanges();


            response.Success = true;
            return Json(response);

        }





        [HttpGet]
        public ActionResult Delete(int Id)
        {

            var grp = _db.AuthGroups.FirstOrDefault(g => g.Id == Id);
            if (grp == null)
            {
                return HttpNotFound();
            }

            if (_db.Users.FirstOrDefault(u => u.AuthGroupId == Id) != null)
            {
                return HttpNotFound();
            }

            _db.AuthGroups.Remove(grp);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

FirstBackEndProj/FirstBackEndProj/Areas/Admin/Views/Group/Create.cshtml
@model List<FirstBackEndProj.Models.AuthAction>
@{
    ViewBag.Title = "Add Group";
}


<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            Add Group
        </div>
        <div class="card-body card-block">
            <form action="@Url.Action("Create", "Group")" method="post" class="form-horizontal" id="group-form">
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="name" class=" form-control-label">Group Name</label>
                    </div>
                    <div class="col-12 col-md-9">
                        <input type="text" id="Name" required name="Name" class="form-control">
                    </div>
                </div>
                <br> <br>
                @foreach (var action in Model)
                {

                    <div class="row form-group action-permission" data-action="@action.Id">
                        <div class="col col-md-3">
                            <label class=" form-control-label">@action.Name</label>
                        </div>
                        <div class="col col-md-9">
                            <div class="form-check-inline form-check">
                                <label for="CanView-@action.Name" class="form-check-label ">
                                    <input type="checkbox" id="CanView-@action.Name" name="CanView" class="form-check-input"> View
                                </label>
                                <label for="CanEdit-@action.Name" class="form-check-label ">
                                    <input type="checkbox" id="CanEdit-@action.Name" name="CanEdit" class="form-check-input"> Edit
                                </label>
                                <label for="CanDelete-@action.Name" class="form-check-label ">
                                    <input type="checkbox" id="CanDelete-@action.Name" name="CanDelete" class="form-check-input"> Delete
                                </label>
                                <label for="OnlyOwner-@action.Name" class="form-check-label ">
                                    <input type="checkbox" id="OnlyOwner-@action.Name" name="OnlyOwner" class="form-check-input"> Owner
                                </label>
                            </div>
                        </div>
                    </div>
                }
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary" btn-sm>
                        Add
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

FirstBackEndProj/FirstBackEndProj/Areas/Admin/Views/Group/Edit.cshtml
@model FirstBackEndProj.Models.AuthGroup
@{
    ViewBag.Title = "Edit";
}




<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            Edit Group
        </div>
        <div class="card-body card-block">
            <form action="@Url.Action("Edit", "Group")" method="post" class="form-horizontal" id="edit-group-form">
                <input type="hidden" name="Id" value="@Model.Id" />
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="name" class=" form-control-label">Group Name</label>
                    </div>
                    <div class="col-12 col-md-9">
                        <input type="text" id="Name" required name="Name" value="@Model.Name" class="form-control">
                    </div>
                </div>
                <br> <br>
                @foreach (var action in ViewBag.Actions)
                {

                    <div class="row form-group action-permission" data-action="@action.Id">
                        <div class="col col-md-3">
                            <label class=" form-control-label">@action.Name</label>
                        </div>
                        <div class="col col-md-9">

                            @{
                                var grpAction = Model.AuthPermissions.FirstOrDefault(p => p.AuthActionId == action.Id);

                            }
                            <div class="form-check-inline form-check">
                                <label for="CanView-@action.Name" class="form-check-label ">
                                    <input type="checkbox" @(grpAction?.CanView == true ? "checked" : " ") id="CanView-@action.Name" name="CanView" class="form-check-input"> View
                                </label>
                                <label for="CanEdit-@action.Name" class="form-check-label ">
                                    <input type="checkbox" @(grpAction?.CanEdit == true ? "checked" : " ") id="CanEdit-@action.Name" name="CanEdit" class="form-check-input"> Edit
                                </label>
                                <label for="CanDelete-@action.Name" class="form-check-label ">
                                    <input type="checkbox" @(grpAction?.CanDelete == true ? "checked" : " ") id="CanDelete-@action.Name" name="CanDelete" class="form-check-input"> Delete
                                </label>
                                <label for="OnlyOwner-@action.Name" class="form-check-label ">
                                    <input type="checkbox" @(grpAction?.OnlyOwner == true ? "checked" : " ") id="OnlyOwner-@action.Name " name="OnlyOwner" class="form-check-input"> Owner
                                </label>
                            </div>
                        </div>
                    </div>
                }
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary" btn-sm>
                        Update
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

FirstBackEndProj/FirstBackEndProj/Areas/Admin/Views/Group/Index.cshtml
@model List<FirstBackEndProj.Models.AuthGroup>
@{
    ViewBag.Title = "Groups";
}

<div class="col-md-12">
    <h3 class="title-5 m-b-35">Groups</h3>
    <div class="table-data__tool">
        <div class="table-data__tool-right">
            <a href="@Url.Action("Create", "Group")" class="au-btn au-btn-icon au-btn--green au-btn--small">
                <i class="zmdi zmdi-plus"></i>Add Group
            </a>
        </div>
    </div>
    <div class="table-responsive table-responsive-data2">
        <table class="table table-data2">
            <thead>
                <tr>
                    <th>Group Name</th>
                    <th>User Email</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var g in Model)
                {
                    <tr class="tr-shadow">
                        <td>@g.Name</td>
                        <td>@String.Join(",", g.Users.Select(u => u.Email).ToArray())</td>

                        <td>
                            <div class="table-data-feature">
                                <a href="@Url.Action("Edit", "Group", new {Id=g.Id })" class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                                    <i class="zmdi zmdi-edit"></i>
                                </a>
                                @if (g.Users.Count == 0)
                                {
                                    <a href="@Url.Action("Delete", "Group", new {Id=g.Id })" class="item delete-group" data-toggle="tooltip" data-placement="top" data-groupid=" @g.Id" title="Delete">
                                        <i class="zmdi zmdi-delete"></i>
                                    </a>
                                }
                            </div>
                        </td>
                    </tr>
                    <tr class="spacer"></tr>

                }
            </tbody>
        </table>
    </div>
    <!-- END DATA TABLE -->
</div>

<script>

    $(document).ready(function () {
        $('a.delete-group').confirm({
            title: "Delete Group",
            content: "Are you sure to delete group?",
            buttons: {
                heyThere: {
                    text: 'Yes',
                    btnClass: 'btn-danger',
                    action: function (heyThereButton) {
                        var groupId = $(this).data("groupid");
                        console.log(groupId);
                        location.href = this.$target.attr('href')

                    }
                },
                no: {
                    text: 'No',
                    btnClass: 'btn-success',
                    action: function (no) {
                    }
                },
            }
        });
    });

</script>